object FrmReverseCallManager: TFrmReverseCallManager
  Left = 0
  Top = 0
  Align = alClient
  BorderStyle = bsNone
  Caption = #21453#21628#26816#27979
  ClientHeight = 444
  ClientWidth = 636
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  Position = poOwnerFormCenter
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  ExplicitWidth = 320
  ExplicitHeight = 240
  PixelsPerInch = 96
  TextHeight = 16
end
