#if !defined(AFX_QNVFILETRANSFER_H__F1AF9B9A_F9B8_432A_9B88_ED1877229B2D__INCLUDED_)
#define AFX_QNVFILETRANSFER_H__F1AF9B9A_F9B8_432A_9B88_ED1877229B2D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// Cqnvfiletransfer wrapper class

class Cqnvfiletransfer : public CWnd
{
protected:
	DECLARE_DYNCREATE(Cqnvfiletransfer)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4453740f, 0xd970, 0x4021, { 0x89, 0xac, 0x41, 0xdc, 0x6f, 0x70, 0x4c, 0x26 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void GetVer(BSTR* strVer);
	void FT_ReleaseSource(long bSelt);
	long FT_StopFileTrans(unsigned long dwType);
	long FT_GetHandle();
	long FT_GetSID();
	long FT_RecvRequest(LPCTSTR lpVID, LPCTSTR lpFileName, unsigned long dwFileLen, unsigned long dwVerType, unsigned long dwFileType, unsigned long dwHandle);
	long FT_ReplyRecvFileRequest(unsigned long dwsid, LPCTSTR lpFileName, unsigned long dwFileLen, long bOverWrite);
	long FT_GetRequestType();
	CString FT_GetFilePath();
	long FT_SendRequest(LPCTSTR lpVID, LPCTSTR lpFilePath,unsigned long dwVerType, unsigned long dwFileType);
	long FT_GetTransFileType();
	long FT_SetBmp2JpgQuality(unsigned long dwQuality);
	long FT_GetFileSize();
	long FT_SetLanguage(unsigned short wLanguage);
	long FT_GetTransStatus();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_QNVFILETRANSFER_H__F1AF9B9A_F9B8_432A_9B88_ED1877229B2D__INCLUDED_)
