//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by qnviccubdemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QNVICCUBDEMO_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_CHANNELCTRL_DIALOG          129
#define IDD_MEDIAPLAY_DIALOG            131
#define IDD_TOOLS_DIALOG                132
#define IDR_MENU1                       133
#define IDD_WAVEFORMAT_DIALOG           135
#define IDD_MEDIAPLAYBUF_DIALOG         136
#define IDD_FAXMODULE_DIALOG            137
#define IDD_INPUTTTS_DIALOG             138
#define IDD_SELECTMULTIFILE_DIALOG      139
#define IDD_SPEECH_DIALOG               140
#define IDD_CONFERENCE_DIALOG           141
#define IDD_REMOTE_DIALOG               142
#define IDD_CCMODULE_DIALOG             143
#define IDR_MENU2                       144
#define IDD_FILETRANSFER_DIALOG         145
#define IDD_BROADCAST_DIALOG            150
#define IDD_INPUTIP_DIALOG              151
#define IDD_RECVBROAD_DIALOG            152
#define IDD_SOCKETCLIENT_DIALOG         154
#define IDD_SOCKETUDP_DIALOG            155
#define IDD_STORAGE_DIALOG              156
#define IDD_CHECKLINE_DIALOG            157
#define IDD_INPUTREMOTE_DIALOG          158
#define IDC_OPENDEV                     1000
#define IDC_CLOSEDEV                    1001
#define IDC_ENABLEHOOK                  1002
#define IDC_ENABLEMIC                   1003
#define IDC_WATCHDOG                    1004
#define IDC_ENABLELINE2SPK              1005
#define IDC_DISABLERING                 1006
#define IDC_DEVSTATUS                   1007
#define IDC_STARTPLAYFILE               1008
#define IDC_STOPPLAYFILE                1009
#define IDC_CHANNELLIST                 1010
#define IDC_MICAM                       1010
#define IDC_STID                        1011
#define IDC_PSTNEnd                     1011
#define IDC_STARTRECFILE                1012
#define IDC_PSTN                        1012
#define IDC_STOPRECFILE                 1013
#define IDC_LOCATION                    1013
#define IDC_COMRECFORMAT                1014
#define IDC_SPKAM                       1015
#define IDC_SELECTLINE                  1016
#define IDC_LINEINAM                    1018
#define IDC_ADCIN                       1019
#define IDC_COMLINE3X                   1020
#define IDC_ENABLEPLAY2SPK              1022
#define IDC_DIALCODE                    1023
#define IDC_STARTDIAL                   1024
#define IDC_STOPDIAL                    1025
#define IDC_OPENFILE                    1026
#define IDC_STOP                        1028
#define IDC_PAUSE                       1029
#define IDC_RESUME                      1030
#define IDC_PLAYSLIDER                  1031
#define IDC_MEDIAPLAY                   1032
#define IDC_DOPLAY                      1033
#define IDC_STARTMULTIPLAY              1034
#define IDC_STOPMULTIPLAY               1035
#define IDC_INITTTSLIST                 1036
#define IDC_CHECKCODETYPE               1037
#define IDC_OPENREMOTE                  1038
#define IDC_PLAY2LINE                   1039
#define IDC_24V                         1040
#define IDC_DOPLAYMUX                   1041
#define IDC_RINGPOWER                   1042
#define IDC_DOPLAYAM                    1043
#define IDC_STARTBUFREC                 1044
#define IDC_STOPRECBUF                  1045
#define IDC_WAVEFORMAT                  1046
#define IDC_VIEWBUF                     1047
#define IDC_STMAXVALUE                  1048
#define IDC_RESETMAX                    1049
#define IDC_BUFECHOED                   1050
#define IDC_FILEECHOED                  1051
#define IDC_STMAX                       1052
#define IDC_STARTPLAYBUF                1054
#define IDC_STOPBUF                     1055
#define IDC_FAXMODULE                   1056
#define IDC_SENDPATH                    1057
#define IDC_SELECTSEND                  1058
#define IDC_RECVPATH                    1059
#define IDC_STARTRECV                   1060
#define IDC_STOPRECV                    1061
#define IDC_VIEWRECV                    1062
#define IDC_STARTSEND                   1063
#define IDC_STOPSEND                    1064
#define IDC_VIEWSEND                    1065
#define IDC_STARTRING                   1069
#define IDC_REFUSE                      1071
#define IDC_FLASH                       1072
#define IDC_LED                         1073
#define IDC_PLAYTTS                     1074
#define IDC_STOPPLAYTTS                 1075
#define IDC_TTS                         1076
#define IDC_ADD                         1078
#define IDC_DEL                         1079
#define IDC_FILELIST                    1080
#define IDC_SPEECH                      1081
#define IDC_SPEECHCONTENT               1082
#define IDC_STARTSPEECHI                1083
#define IDC_STARTSPEECHE                1084
#define IDC_STOPSPEECH                  1085
#define IDC_STARTSPEECHMIC              1086
#define IDC_SPEECHRESULT                1087
#define IDC_THRESHOLD                   1088
#define IDC_SETTHRESHOLD                1089
#define IDC_SILENCEAM                   1090
#define IDC_SETSILENCEAM                1091
#define IDC_INLIST                      1094
#define IDC_OUTLIST                     1095
#define IDC_STCONFID                    1096
#define IDC_STARTREC                    1097
#define IDC_STOPREC                     1098
#define IDC_SELECTDIR                   1099
#define IDC_BROWER                      1100
#define IDC_UPLOADFILEPATH              1101
#define IDC_SELECT                      1102
#define IDC_URL                         1103
#define IDC_UPLOAD                      1104
#define IDC_CCNUMBER                    1105
#define IDC_CCPWD                       1106
#define IDC_LOGON                       1107
#define IDC_LOGOUT                      1108
#define IDC_STSTATUS                    1109
#define IDC_CCSTATUS                    1110
#define IDC_CALLCC                      1111
#define IDC_STARTCALL                   1112
#define IDC_STOPCALL                    1113
#define IDC_ANSWER                      1114
#define IDC_CHANNELID                   1118
#define IDC_LINEOUT                     1119
#define IDC_FIELPATH                    1120
#define IDC_BROWERFILE                  1121
#define IDC_MSGTEXT                     1122
#define IDC_SENDMSG                     1123
#define IDC_SENDCMD                     1124
#define IDC_REGCCNUM                    1125
#define IDC_REGCC                       1126
#define IDC_REGPWD                      1127
#define IDC_REGNICK                     1128
#define IDC_SETSERVER                   1129
#define IDC_SERVERADDR                  1130
#define IDC_SELECTFILE                  1132
#define IDC_DESTCC                      1134
#define IDC_RECVFILE                    1136
#define IDC_VOLUME                      1141
#define IDC_SETVOLUME                   1142
#define IDC_DISABLEMIC                  1145
#define IDC_DISABLESPK                  1146
#define IDC_MICVOLUME                   1147
#define IDC_DISABLEECHO                 1150
#define IDC_SVRID                       1151
#define IDC_DISABLEUPLOAD               1152
#define IDC_DISABLEDOWNLOAD             1153
#define IDC_RECFILEAGC                  1154
#define IDC_IPLIST                      1155
#define IDC_STARTBROAD                  1158
#define IDC_STOPBROAD                   1159
#define IDC_COMBOCHANNEL                1160
#define IDC_IPADDR                      1161
#define IDC_SAVEPARAM                   1165
#define IDC_READPARAM                   1166
#define IDC_STARTCONNECT                1167
#define IDC_STOPCONNECT                 1168
#define IDC_SVRIPADDR                   1169
#define IDC_SVRPORT                     1170
#define IDC_SOCKETSTATUS                1171
#define IDC_DATA                        1172
#define IDC_SEND                        1173
#define IDC_UPLOADLOG                   1174
#define IDC_SAVEFILEPATH                1175
#define IDC_DOWNLOADURL                 1176
#define IDC_DOWNLOAD                    1177
#define IDC_BUFAM                       1179
#define IDC_STOREAGEDATA                1180
#define IDC_READ                        1181
#define IDC_WRITE                       1182
#define IDC_READSRC                     1183
#define IDC_READNEW                     1184
#define IDC_READPWD                     1185
#define IDC_WRITEPWD                    1186
#define IDC_WRITESRC                    1187
#define IDC_WRITENEW                    1188
#define IDC_MODIFYREAD                  1189
#define IDC_MODIFYWRITE                 1190
#define IDC_STOREAGEDATAREAD            1191
#define IDC_SETCHANNLE                  1192
#define IDC_STCHIPTYPE                  1193
#define IDC_STARTCHECKLINE              1195
#define IDC_STARTLINEERR                1196
#define IDC_ASYNCHECK                   1197
#define IDC_STSEAP                      1198
#define IDC_STSEAP2                     1199
#define IDC_PLAYREMOTE                  1200
#define IDC_REMOTEFILE                  1201
#define IDC_STTOTALPLAY                 1203
#define IDC_STTOTALLEN                  1204
#define IDC_RECVFSK                     1207
#define IDC_RECVDTMF                    1208
#define IDC_RECVSIGN                    1209
#define IDC_RECVCALLIN                  1210
#define IDC_FINDSVR                     1211
#define IDC_SETSERVERNAME               1212
#define IDC_SERVERNAME                  1214
#define IDC_FINDSERVERNAME              1215
#define IDC_FINDPORT                    1216
#define IDC_STARTFIND                   1217
#define IDC_STOPFIND                    1218
#define IDC_SENDDTMF                    1220
#define IDC_SENDFSK                     1221
#define IDC_ADFUNC                      1223
#define IDC_EXCLUSIVE                   1224
#define IDC_MODIFYPWD                   1225
#define IDC_OLDPWD                      1226
#define IDC_NEWPWD                      1227
#define IDC_STARTFILESPEECH             1228
#define IDC_GENDER                      1229
#define IDC_SETGENDER                   1230
#define ID_MENU_TOOLS                   32771
#define ID_MENU_CONFERENCE              32772
#define ID_MENU_REMOTE                  32773
#define ID_MENU_CCMODULE                32774
#define ID_MENU_FIELTRANSFER            32775
#define ID_MENU_RECVFAX                 32776
#define ID_MENU_SENDFAX                 32777
#define ID_MENU_FAXLOG                  32778
#define ID_MENU_BROADCAST               32779
#define ID_MENU_RECVBROAD               32780
#define ID_MENU_SOCKETCLIENT            32781
#define ID_MENU_SOCKETUDP               32782
#define ID_MENU_STORAGE                 32783
#define ID_MENU_CHECKLINE               32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1231
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
